spring:
  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/okoyo-store-db?useSSL=false
#    password:
     username: tamielkasyade
     password: Vfrcsv_2005
     url: jdbc:mysql://okoyo-store.mysql.database.azure.com:3306/okoyo-store-db
     ssl-mode: REQUIRED
  mail:
    protocol: smtp
    host: smtp-mail.outlook.com
    username: kawaiistore00@outlook.com
    password: Vfrcsv2005
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/

server:
  port: 8084

