#name: AzureSpringCloud
#on: push
#env:
#  ASC_PACKAGE_PATH: ${{ github.workspace }}
#  JAVA_VERSION: 18
#  AZURE_SUBSCRIPTION: 174b7a78-ef38-46eb-a049-7d9f11fe9856
#
#jobs:
#  deploy_to_production:
#    runs-on: ubuntu-latest
#    name: deploy to production with artifact
#    steps:
#      - name: Checkout Github Action
#        uses: actions/checkout@v2
#
#      - name: Set up JDK ${{ env.JAVA_VERSION }}
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#
#      - name: maven build, clean
#        run: |
#          mvn clean package -DskipTests
#
#      - name: Login via Azure CLI
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: deploy to production with artifact
#        uses: azure/spring-cloud-deploy@v1
#        with:
#          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
#          action: Deploy
#          service-name: okoyo-store
#          app-name: website-okoyo-store
#          use-staging-deployment: false
#          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar

name: AzureSpringApps
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 174b7a78-ef38-46eb-a049-7d9f11fe9856

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: okoyo-store
          app-name: website-okoyo-store
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar